export enum StatusSolicitacao {
    SOLICITADO = 'SOLICITADO',
    APROVADO = 'APROVADO',
    RECUSADO = 'RECUSADO',
    AGUARDANDO_CALCULO = 'AGUARDANDO_CALCULO',
    AGUARDANDO_VALORES = 'AGUARDANDO_VALORES',
    AGUARDANDO_EMPENHO = 'AGUARDANDO_EMPENHO',
    FINALIZADO = 'FINALIZADO',

}